name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Build, Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
      - run: npm ci
      - run: npm run build
      - name: Archive
        run: |
          mv build ${{ github.event.repository.name }}-${{ github.ref_name }}
          zip -9r ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }}-${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip